baseURL = "https://finbits.io"
languageCode = "en-us"
title = "FinBits"
theme = "mediumish"
summaryLength = 25
copyright = "finbits.io - All rights reserved"
disqusShortname = "finbits-io"
googleAnalytics = "UA-133194833-1"

[params]
  #logo = "/images/finbits.png"
  description ="A blog by Randy Findley about software engineering, parenting, and coooking."
  mailchimp = "https://finbits.us20.list-manage.com/subscribe/post?u=0f73aadf04d1683fa8b417ffd&amp;id=b5004f6887"
  mailprotect = "b_0f73aadf04d1683fa8b417ffd_b5004f6887"

[params.author]
  name = "Randy Findley"
  thumbnail = "/images/randy-findley.jpeg"
  description = "Loves his wife, kids, & building software..."

[params.index]
  picture = "/images/randy-findley.jpeg"
  title = "Randy Findley"
  subtitle = "I love my wife, my kids, & building software.  I also like cooking soup."
  mdtext = '''
Thanks for stumbling upon my blog.  
Please join me as I navigate this life as a father, software engineer, and chef.
'''
  alertbar = true

[params.social]
  github = "rgfindl"
  linkedin = "randyfindley"
  medium = "rgfindley"
  twitter = "rgfindl"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"